### PR TITLE
allow set "multiple" DaysOfWeek for alarms

### PR DESCRIPTION
**Pull request by ricardojlrufino**
Each BIT is a Enabled DayOfWeek, like: 
MondayToFriday  = B00111110.
LSB is sunday

Sample for a HTML Page:
```
                          <select>
                            <option value="62">Seg a Sex</option>
                            <option value="65">Sab e Dom</option>
                            <option value="1">Domingo</option>
                            <option value="2">Segunda</option>
                            <option value="4">Terça</option>
                            <option value="8">Quarta</option>
                            <option value="16">Quinta</option>
                            <option value="32">Sex</option>
                            <option value="64">Sab</option>
                          </select>
```
String doweek = server.arg("doweek");
Alarm.alarmRepeat(doweek.toInt(), hour,minute,0, onStartAlarm);

### CODE REVIEW

**Comment by jhagberg** [comment]
I think you should suggest this changes to the original TimeAlarm library.

**Comment by ricardojlrufino** [comment]
Are not they different libs today?

**Comment by jhagberg** [comment]
This is a fork from the original library. With just ESP8266 changes. I think it is best that none ESP8266 changes are submitted to the original library and if they are approved I can update from them.

**Comment by jhagberg** [comment]
Make a pull request here https://github.com/PaulStoffregen/TimeAlarms

**Comment by jhagberg** [comment]
@ricardojlrufino have you seen this pull ? https://github.com/PaulStoffregen/TimeAlarms/pull/44

**Pull request closed without merging**
